KappaSigmaMu/kappasigmamu.github.io

cypress.json
cypress/fixtures/example.json
cypress/integration/1-getting-started/navbar.ts
cypress/plugins/index.js
cypress/support/commands.js
cypress/support/index.js
cypress/tsconfig.json
package.json
tsconfig.json
yarn.lock

Hello :rabbit: 
This is a PR to add and config cypress to the project, already using typescript. Also, a first test example was made.
1. Run `yarn` to install the new dependency
2. Run `yarn cy:open`
PS: Cypress uses the default `localhost:3000/ksm-app` address (see `cypress.json`). If you change the port, the tests will fail.

Add and config Cypress

---

src/App.tsx
src/index.scss

This PR modifies some theme colors of bootstrap.

Add custom scss theme colors to bootstrap

---

src/components/AccountSelector.tsx
src/components/navbar/index.tsx
src/styles/index.scss
src/substrate/SubstrateContext.tsx

Hey there, 
In this PR, the account selector is implemented. The styling is to be disconsidered given that it will be changed later on.

Implement account selector

---

.eslintrc.js
src/components/timer/index.tsx
src/hooks/useBlockTime.ts
src/pages/About.tsx

Hello :rabbit: 
This is a PR to add the component that displays the current round timer. For now, it just prints the time left in days/hours and in percentage, but in the future, when the design is ready, it will display in a beautiful way.
PS: For testing purposes, the TImer is being rendered in the About page, will be removed before the merge.
PS²: Enabling `Api` to be `null` caused a lot of problems, I think we will need to fix it and do not permit `null`. I had to disable `ts` in the `useBlockTime` hook because of it.
Go to the About page

[COMPONENT] Implement the current round timer

---

.eslintrc.js
package.json
src/components/CurrentRoundRow.tsx
src/hooks/useConsts.ts
src/pages/Home.tsx
yarn.lock

Hey!
In this PR we introduce the CurrentRoundRow component:
TODO:

WIP: Add CurrentRoundRow

---

package.json
src/pages/App.tsx
src/pages/CyborgGuide.tsx
src/pages/Home.tsx
src/pages/Human.tsx
src/pages/Welcome.tsx
src/types/global.d.ts
tsconfig.json

Extract NavRoute to simplify Navbar manipulation with react-router. This is the first step of a bigger refactoring.

Make it easier to manipulate Navbar

---

src/account/AccountContext.tsx
src/components/AccountSelector.tsx
src/helpers/fetchAccounts.ts

This PR introduces a Spinner component while AccountSelector is loading.

Render Spinner while AccountSelector is loading

---

.github/workflows/main.yml
src/__tests__/components/__snapshots__/BidsList.test.tsx.snap
src/__tests__/helpers/accountId.test.ts
src/__tests__/helpers/truncate.test.ts
src/components/AccountSelector.tsx
src/components/BidsList.tsx
src/helpers/accountId.ts
src/helpers/humanize.ts
src/helpers/truncate.ts

Truncate accountId

---

src/components/AccountSelector.tsx

Deliver https://github.com/KappaSigmaMu/kappasigmamu.github.io/issues/55

Add Identicon to AccountSelector

---

src/pages/CyborgGuide.tsx

Hey there,
In this PR, the external links are added to the Cyborg page.

Add missing external urls

---

src/components/Navbar.tsx
src/components/__tests__/__snapshots__/Navbar.test.tsx.snap
src/pages/App.tsx
src/pages/explore/BiddersPage/__tests__/BidsList.test.tsx

Improve Navbar rendering

---

.gitignore
Dockerfile
README.md
docker-compose.yml
package.json
src/helpers/fetchAccounts.ts
src/kusama/config/development.json
yarn.lock

This PR adds a Dockerfile for the application and a docker-compose.yaml to combine the frontend with a development node. This development node has very fast rotation times and 6 members in its initial state. Instructions on how to run it were added to README.md.

Dockerize frontend and substrate development node

---

package.json
src/components/MemberOffcanvas.tsx
src/pages/LandingPage.tsx
src/styles/globalStyle.ts
yarn.lock

- Update `canary-component` dependency to be able to use the new `onNodeClick` callback
- Add an `OffCanvas` component to show node/member data when image/title of active node is clicked
- Style `OffCanvas` component matching KSM style guide:

Add OffCanvas dialog for active canary node

---

src/pages/explore/ExplorePage.tsx

This PR fixes an error that was introduced when implementing real-time member loading.

Fix member labels

---

src/components/AccountIndex.tsx
src/components/MemberIdentity.tsx
src/pages/explore/MembersPage/components/MembersList.tsx
src/pages/explore/MembersPage/index.tsx

Show member identity if set otherwise show member hash

---

src/pages/explore/BiddersPage/index.tsx
src/pages/explore/ExplorePage.tsx

Also inject `api` object like done for other pages.

Set bidders list as default explore page

---

.eslintrc.js
src/__tests__/fixtures/PalletSocietyBidFixture.ts
src/helpers/__tests__/humanize.test.ts
src/helpers/humanize.ts
src/pages/explore/BiddersPage/BidVouch.tsx
src/pages/explore/BiddersPage/BiddersList.tsx
src/pages/explore/BiddersPage/__tests__/__snapshots__/BiddersList.test.tsx.snap
src/pages/explore/BiddersPage/helper.ts
src/pages/explore/BiddersPage/index.tsx

Bonjour,
In this PR, the vounch/unvouch component is implemented. Also, the bid, unbid, vouch and unvouch extrinsics were extracted into a helper, since their responses and inputs are pretty much the same and can be abstracted.

Implement vouch component and extract extrinsics into a helper

---

src/account/AccountContext.tsx
src/pages/App.tsx

... by skipping api loading.
Also add loading spinner to pages using the api.

Optimize guide loading time

---

src/__tests__/fixtures/PalletSocietyBidFixture.ts
src/components/SocialIcons.tsx
src/components/__tests__/__snapshots__/Navbar.test.tsx.snap
src/pages/CyborgGuidePage.tsx
src/pages/explore/BiddersPage/__tests__/BiddersList.test.tsx
src/pages/explore/BiddersPage/index.tsx
src/pages/explore/components/__tests__/NavigationBar.test.tsx
src/pages/explore/components/__tests__/__snapshots__/NavigationBar.test.tsx.snap

Video showing before/after:
https://user-images.githubusercontent.com/1481940/177060237-868d6a73-afaf-457f-a0d0-103ad8b60727.mp4
Also, after recording I added some text shadows to guide links on mobile so they become easier to read.

Make cyborg guide responsive

---

src/components/MemberIdentity.tsx
src/pages/App.tsx
src/pages/explore/CandidatesPage/components/CandidateDetailsOffcanvas.tsx
src/pages/explore/CandidatesPage/components/CandidatesList.tsx
src/pages/explore/ExplorePage.tsx
src/pages/explore/MembersPage/components/MemberDetailsOffcanvas.tsx
src/pages/explore/MembersPage/components/MembersList.tsx
src/pages/explore/components/AccountHeader.tsx
src/pages/explore/components/NavigationBar.tsx
src/pages/explore/components/Offcanvas.tsx
src/pages/explore/components/__tests__/__snapshots__/NavigationBar.test.tsx.snap

Create candidate details drawer with skeptics list

---

src/pages/App.tsx
src/pages/GilbertoGilPage.tsx

This is already deployed on production

Create Gil historical page

---

.gitignore
README.md
config/kusama.yml
package.json
src/components/AccountSelector.tsx
src/pages/explore/CandidatesPage/components/CandidateDetailsOffcanvas.tsx
src/pages/explore/CandidatesPage/components/CandidatesList.tsx

This PR adds Chopsticks to the project, including the config file, a new command and a brief documentation

Add Chopsticks to the project to make our lives easier :)

---

src/pages/explore/CandidatesPage/components/CandidatesList.tsx
src/pages/explore/CandidatesPage/components/VoteButton.tsx
src/pages/explore/ExplorePage.tsx
src/pages/explore/MembersPage/components/MembersList.tsx
src/pages/explore/MembersPage/index.tsx
src/pages/explore/components/NavigationBar.tsx
src/pages/explore/helpers.ts
src/types/global.d.ts

This PR also adds:
- Total of bids, candidates and members in the overview
- Sort by ranked members and add badge to their rows

Add buttons to vote for the defender

---

.env.development.sample
.env.production
.env.test
config/kusama.yml.sample
package.json
src/components/LinkWithQuery.tsx
src/components/LoadingContainer.tsx
src/components/Navbar.tsx
src/components/NavigateWithQuery.tsx
src/components/NextStep.tsx
src/components/SettingsDropdown.tsx
src/helpers/providers.ts
src/kusama/KusamaContext.tsx
src/pages/FuturivelPage.tsx
src/pages/GilbertoGilPage.tsx
src/pages/LandingPage.tsx
src/pages/WelcomePage.tsx
src/pages/explore/ExplorePage.tsx
src/pages/explore/components/NavigationBar.tsx
yarn.lock

This PR adds a Settings dropdown menu to the NavBar that lets the user switch between different RPC providers. The change is done using query strings and persisted throughout the application

Let the use choose RPC provider

---

src/helpers/extrinsics.ts
src/pages/explore/BiddersPage/BidVouch.tsx

Hey,
This PR simply disables the submit button for bid and vouch, also showing the "Awaiting signature." message for the user.

Disable submit btn and show info when awaiting for signature in tx

---

src/pages/explore/ProofOfInkPage/ExamplesPage.tsx
src/pages/explore/ProofOfInkPage/NextHeadPage.tsx
src/pages/explore/ProofOfInkPage/index.tsx
src/pages/explore/components/NavigationBar.tsx

Show next head in proof of ink
